### ISSUE TITLE
Step5Error: List index out of range

### ISSUE THREAD

**Issue by TobyBaril** [niccw/repeatcraftp#1]
In file.rclabel.gff, `##repeatcraft` appears at the end of the file (last line) rather than second line, causing the below error:

`Traceback (most recent call last):
  File "/home/toby/Programs/repeatCraft/repeatcraft.py", line 161, in <module>
    truemergeltrm.trumergeLTR(rmgff=outputnamelabel, outfile="ltrmerge.tmp.gff")
  File "/home/toby/Programs/repeatCraft/helper/truemergeltrm.py", line 47, in trumergeLTR
    ltrgroup = re.findall(r"LTRgroup=(.*)$", col[8])`
 
I temporarily solved this in my analysis by removing `##repeatcraft` from file.rclabel.gff

**Comment by niccw** [comment]
Thanks for reporting it.
Should be the same bug you reported in #2, fixed in 136c2d2
